// <auto-generated />
// Source: heyrafiki/openapi@327e0a70de92771d3930380ce552c00e0ed8fc52
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Heyrafiki.Models;

public sealed class ApiInformation
{
    [JsonPropertyName("object")]
    public string Object { get; set; } = "api";

    [JsonPropertyName("version")]
    public string Version { get; set; } = "v1";

    [JsonPropertyName("environment")]
    public string Environment { get; set; } = string.Empty;

    [JsonPropertyName("resources")]
    public IReadOnlyList<string> Resources { get; set; } = Array.Empty<string>();
}

public sealed class PractitionerList
{
    [JsonPropertyName("object")]
    public string Object { get; set; } = "list";

    [JsonPropertyName("data")]
    public IReadOnlyList<Practitioner> Data { get; set; } = Array.Empty<Practitioner>();

    [JsonPropertyName("has_more")]
    public bool HasMore { get; set; }
}

public sealed class PractitionerLocation
{
    [JsonPropertyName("city")]
    public string City { get; set; } = string.Empty;

    [JsonPropertyName("country")]
    public string Country { get; set; } = string.Empty;
}

public sealed class PractitionerSessionFee
{
    [JsonPropertyName("amount")]
    public long Amount { get; set; }

    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;
}

public sealed class Practitioner
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "practitioner";

    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("profession")]
    public string Profession { get; set; } = string.Empty;

    [JsonPropertyName("location")]
    public PractitionerLocation Location { get; set; } = new PractitionerLocation();

    [JsonPropertyName("session_fee")]
    public PractitionerSessionFee SessionFee { get; set; } = new PractitionerSessionFee();
}

public sealed class PractitionerAvailabilityWeeklyHoursItem
{
    [JsonPropertyName("weekday")]
    public long Weekday { get; set; }

    [JsonPropertyName("start")]
    public string Start { get; set; } = string.Empty;

    [JsonPropertyName("end")]
    public string End { get; set; } = string.Empty;

    [JsonPropertyName("formats")]
    public IReadOnlyList<string> Formats { get; set; } = Array.Empty<string>();
}

public sealed class PractitionerAvailability
{
    [JsonPropertyName("object")]
    public string Object { get; set; } = "availability";

    [JsonPropertyName("practitioner_id")]
    public string PractitionerId { get; set; } = string.Empty;

    [JsonPropertyName("timezone")]
    public string Timezone { get; set; } = string.Empty;

    [JsonPropertyName("weekly_hours")]
    public IReadOnlyList<PractitionerAvailabilityWeeklyHoursItem> WeeklyHours { get; set; } = Array.Empty<PractitionerAvailabilityWeeklyHoursItem>();
}

public sealed class BookingList
{
    [JsonPropertyName("object")]
    public string Object { get; set; } = "list";

    [JsonPropertyName("data")]
    public IReadOnlyList<Booking> Data { get; set; } = Array.Empty<Booking>();

    [JsonPropertyName("has_more")]
    public bool HasMore { get; set; }
}

public sealed class Booking
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "booking";

    [JsonPropertyName("session_id")]
    public string SessionId { get; set; } = string.Empty;

    [JsonPropertyName("practitioner_id")]
    public string PractitionerId { get; set; } = string.Empty;

    [JsonPropertyName("starts_at")]
    public DateTimeOffset StartsAt { get; set; }

    [JsonPropertyName("ends_at")]
    public DateTimeOffset EndsAt { get; set; }

    [JsonPropertyName("timezone")]
    public string Timezone { get; set; } = string.Empty;

    [JsonPropertyName("format")]
    public string Format { get; set; } = string.Empty;

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("payment_source")]
    public string PaymentSource { get; set; } = string.Empty;
}

public sealed class BookingInput
{
    [JsonPropertyName("practitioner_id")]
    public string PractitionerId { get; set; } = string.Empty;

    [JsonPropertyName("starts_at")]
    public DateTimeOffset StartsAt { get; set; }

    [JsonPropertyName("ends_at")]
    public DateTimeOffset EndsAt { get; set; }

    [JsonPropertyName("format")]
    public string Format { get; set; } = string.Empty;

    [JsonPropertyName("payment_source")]
    public string PaymentSource { get; set; } = string.Empty;
}

public sealed class SessionList
{
    [JsonPropertyName("object")]
    public string Object { get; set; } = "list";

    [JsonPropertyName("data")]
    public IReadOnlyList<Session> Data { get; set; } = Array.Empty<Session>();

    [JsonPropertyName("has_more")]
    public bool HasMore { get; set; }
}

public sealed class Session
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "session";

    [JsonPropertyName("practitioner_id")]
    public string PractitionerId { get; set; } = string.Empty;

    [JsonPropertyName("starts_at")]
    public DateTimeOffset StartsAt { get; set; }

    [JsonPropertyName("ends_at")]
    public DateTimeOffset EndsAt { get; set; }

    [JsonPropertyName("timezone")]
    public string Timezone { get; set; } = string.Empty;

    [JsonPropertyName("format")]
    public string Format { get; set; } = string.Empty;

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("payment_source")]
    public string PaymentSource { get; set; } = string.Empty;
}

public sealed class EligibilityCheckInput
{
    [JsonPropertyName("member_reference")]
    public string MemberReference { get; set; } = string.Empty;

    [JsonPropertyName("service_code")]
    public string ServiceCode { get; set; } = string.Empty;

    [JsonPropertyName("scheduled_at")]
    public DateTimeOffset ScheduledAt { get; set; }

    [JsonPropertyName("amount")]
    public long Amount { get; set; }

    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;
}

public sealed class EligibilityCheckService
{
    [JsonPropertyName("code")]
    public string Code { get; set; } = string.Empty;

    [JsonPropertyName("scheduled_at")]
    public DateTimeOffset ScheduledAt { get; set; }
}

public sealed class EligibilityCheckAmount
{
    [JsonPropertyName("requested")]
    public long Requested { get; set; }

    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    [JsonPropertyName("maximum_per_session")]
    public long? MaximumPerSession { get; set; }
}

public sealed class EligibilityCheck
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "eligibility_check";

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("reason_codes")]
    public IReadOnlyList<string> ReasonCodes { get; set; } = Array.Empty<string>();

    [JsonPropertyName("service")]
    public EligibilityCheckService Service { get; set; } = new EligibilityCheckService();

    [JsonPropertyName("amount")]
    public EligibilityCheckAmount Amount { get; set; } = new EligibilityCheckAmount();

    [JsonPropertyName("authorization_required")]
    public bool AuthorizationRequired { get; set; }

    [JsonPropertyName("remaining_sessions")]
    public long? RemainingSessions { get; set; }

    [JsonPropertyName("coverage_valid_until")]
    public DateTimeOffset? CoverageValidUntil { get; set; }

    [JsonPropertyName("checked_at")]
    public DateTimeOffset CheckedAt { get; set; }
}

public sealed class CoverageObservationInput
{
    [JsonPropertyName("source_contract_reference")]
    public string SourceContractReference { get; set; } = string.Empty;

    [JsonPropertyName("external_coverage_reference")]
    public string ExternalCoverageReference { get; set; } = string.Empty;

    [JsonPropertyName("source_version")]
    public string SourceVersion { get; set; } = string.Empty;

    [JsonPropertyName("tenant_reference")]
    public string TenantReference { get; set; } = string.Empty;

    [JsonPropertyName("member_reference")]
    public string MemberReference { get; set; } = string.Empty;

    [JsonPropertyName("plan_name")]
    public string PlanName { get; set; } = string.Empty;

    [JsonPropertyName("service_code")]
    public string ServiceCode { get; set; } = string.Empty;

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    [JsonPropertyName("amount_limit")]
    public long AmountLimit { get; set; }

    [JsonPropertyName("remaining_sessions")]
    public long RemainingSessions { get; set; }

    [JsonPropertyName("authorization_required")]
    public bool AuthorizationRequired { get; set; }

    [JsonPropertyName("coordination_priority")]
    public long? CoordinationPriority { get; set; }

    [JsonPropertyName("valid_from")]
    public DateTimeOffset ValidFrom { get; set; }

    [JsonPropertyName("valid_until")]
    public DateTimeOffset ValidUntil { get; set; }

    [JsonPropertyName("observed_at")]
    public DateTimeOffset ObservedAt { get; set; }

    [JsonPropertyName("evidence_references")]
    public IReadOnlyList<string> EvidenceReferences { get; set; } = Array.Empty<string>();
}

public sealed class CoverageObservationAmountLimit
{
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    [JsonPropertyName("value")]
    public long Value { get; set; }
}

public sealed class CoverageObservation
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "coverage_observation";

    [JsonPropertyName("coverage_id")]
    public string CoverageId { get; set; } = string.Empty;

    [JsonPropertyName("source")]
    public string Source { get; set; } = string.Empty;

    [JsonPropertyName("source_contract_reference")]
    public string SourceContractReference { get; set; } = string.Empty;

    [JsonPropertyName("external_coverage_reference")]
    public string ExternalCoverageReference { get; set; } = string.Empty;

    [JsonPropertyName("source_version")]
    public string SourceVersion { get; set; } = string.Empty;

    [JsonPropertyName("snapshot_version")]
    public long SnapshotVersion { get; set; }

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("service_code")]
    public string ServiceCode { get; set; } = string.Empty;

    [JsonPropertyName("amount_limit")]
    public CoverageObservationAmountLimit AmountLimit { get; set; } = new CoverageObservationAmountLimit();

    [JsonPropertyName("remaining_sessions")]
    public long RemainingSessions { get; set; }

    [JsonPropertyName("authorization_required")]
    public bool AuthorizationRequired { get; set; }

    [JsonPropertyName("coordination_priority")]
    public long? CoordinationPriority { get; set; }

    [JsonPropertyName("valid_from")]
    public DateTimeOffset ValidFrom { get; set; }

    [JsonPropertyName("valid_until")]
    public DateTimeOffset ValidUntil { get; set; }

    [JsonPropertyName("observed_at")]
    public DateTimeOffset ObservedAt { get; set; }
}

public sealed class CoverageBatchRecordInput
{
    [JsonPropertyName("coverage_reference")]
    public string CoverageReference { get; set; } = string.Empty;

    [JsonPropertyName("record_version")]
    public string RecordVersion { get; set; } = string.Empty;

    [JsonPropertyName("tenant_reference")]
    public string TenantReference { get; set; } = string.Empty;

    [JsonPropertyName("member_reference")]
    public string MemberReference { get; set; } = string.Empty;

    [JsonPropertyName("plan_name")]
    public string PlanName { get; set; } = string.Empty;

    [JsonPropertyName("service_code")]
    public string ServiceCode { get; set; } = string.Empty;

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    [JsonPropertyName("amount_limit")]
    public long AmountLimit { get; set; }

    [JsonPropertyName("remaining_sessions")]
    public long RemainingSessions { get; set; }

    [JsonPropertyName("authorization_required")]
    public bool AuthorizationRequired { get; set; }

    [JsonPropertyName("coordination_priority")]
    public long? CoordinationPriority { get; set; }

    [JsonPropertyName("valid_from")]
    public DateTimeOffset ValidFrom { get; set; }

    [JsonPropertyName("valid_until")]
    public DateTimeOffset ValidUntil { get; set; }
}

public sealed class CoverageBatchInput
{
    [JsonPropertyName("contract_version")]
    public string ContractVersion { get; set; } = "2026-08-01";

    [JsonPropertyName("batch_reference")]
    public string BatchReference { get; set; } = string.Empty;

    [JsonPropertyName("batch_version")]
    public string BatchVersion { get; set; } = string.Empty;

    [JsonPropertyName("source_contract_reference")]
    public string SourceContractReference { get; set; } = string.Empty;

    [JsonPropertyName("generated_at")]
    public DateTimeOffset GeneratedAt { get; set; }

    [JsonPropertyName("records")]
    public IReadOnlyList<CoverageBatchRecordInput> Records { get; set; } = Array.Empty<CoverageBatchRecordInput>();
}

public sealed class CoverageBatchResult
{
    [JsonPropertyName("object")]
    public string Object { get; set; } = "coverage_batch_result";

    [JsonPropertyName("batch_reference")]
    public string BatchReference { get; set; } = string.Empty;

    [JsonPropertyName("artifact_sha256")]
    public string ArtifactSha256 { get; set; } = string.Empty;

    [JsonPropertyName("total")]
    public long Total { get; set; }

    [JsonPropertyName("recorded")]
    public long Recorded { get; set; }

    [JsonPropertyName("replayed")]
    public long Replayed { get; set; }

    [JsonPropertyName("observations")]
    public IReadOnlyList<CoverageObservation> Observations { get; set; } = Array.Empty<CoverageObservation>();
}

public sealed class PreauthorizationInput
{
    [JsonPropertyName("eligibility_check_id")]
    public string EligibilityCheckId { get; set; } = string.Empty;

    [JsonPropertyName("booking_id")]
    public string BookingId { get; set; } = string.Empty;
}

public sealed class PreauthorizationAmount
{
    [JsonPropertyName("requested")]
    public long Requested { get; set; }

    [JsonPropertyName("approved")]
    public long? Approved { get; set; }

    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;
}

public sealed class Preauthorization
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "preauthorization";

    [JsonPropertyName("eligibility_check_id")]
    public string EligibilityCheckId { get; set; } = string.Empty;

    [JsonPropertyName("booking_id")]
    public string BookingId { get; set; } = string.Empty;

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("reason_codes")]
    public IReadOnlyList<string> ReasonCodes { get; set; } = Array.Empty<string>();

    [JsonPropertyName("amount")]
    public PreauthorizationAmount Amount { get; set; } = new PreauthorizationAmount();

    [JsonPropertyName("valid_until")]
    public DateTimeOffset? ValidUntil { get; set; }

    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; set; }

    [JsonPropertyName("decision")]
    public PreauthorizationDecision? Decision { get; set; }
}

public sealed class PreauthorizationDecisionPolicy
{
    [JsonPropertyName("reference")]
    public string Reference { get; set; } = string.Empty;

    [JsonPropertyName("version")]
    public string Version { get; set; } = string.Empty;
}

public sealed class PreauthorizationDecision
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "preauthorization_decision";

    [JsonPropertyName("version")]
    public long Version { get; set; }

    [JsonPropertyName("outcome")]
    public string Outcome { get; set; } = string.Empty;

    [JsonPropertyName("reason_codes")]
    public IReadOnlyList<string> ReasonCodes { get; set; } = Array.Empty<string>();

    [JsonPropertyName("policy")]
    public PreauthorizationDecisionPolicy Policy { get; set; } = new PreauthorizationDecisionPolicy();

    [JsonPropertyName("authority_reference")]
    public string AuthorityReference { get; set; } = string.Empty;

    [JsonPropertyName("evidence_references")]
    public IReadOnlyList<string> EvidenceReferences { get; set; } = Array.Empty<string>();

    [JsonPropertyName("decided_at")]
    public DateTimeOffset DecidedAt { get; set; }
}

public sealed class ClaimList
{
    [JsonPropertyName("object")]
    public string Object { get; set; } = "list";

    [JsonPropertyName("data")]
    public IReadOnlyList<Claim> Data { get; set; } = Array.Empty<Claim>();

    [JsonPropertyName("has_more")]
    public bool HasMore { get; set; }
}

public sealed class ClaimAmount
{
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    [JsonPropertyName("billed")]
    public long Billed { get; set; }

    [JsonPropertyName("approved")]
    public long? Approved { get; set; }

    [JsonPropertyName("remitted")]
    public long? Remitted { get; set; }

    [JsonPropertyName("settled")]
    public long? Settled { get; set; }
}

public sealed class ClaimServicePeriod
{
    [JsonPropertyName("starts_at")]
    public DateTimeOffset StartsAt { get; set; }

    [JsonPropertyName("ends_at")]
    public DateTimeOffset EndsAt { get; set; }
}

public sealed class Claim
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "claim";

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("provider_claim_reference")]
    public string? ProviderClaimReference { get; set; }

    [JsonPropertyName("submission_version")]
    public long SubmissionVersion { get; set; }

    [JsonPropertyName("amount")]
    public ClaimAmount Amount { get; set; } = new ClaimAmount();

    [JsonPropertyName("service_period")]
    public ClaimServicePeriod ServicePeriod { get; set; } = new ClaimServicePeriod();

    [JsonPropertyName("lines")]
    public IReadOnlyList<ClaimLine> Lines { get; set; } = Array.Empty<ClaimLine>();

    [JsonPropertyName("information_requests")]
    public IReadOnlyList<ClaimInformationRequest> InformationRequests { get; set; } = Array.Empty<ClaimInformationRequest>();

    [JsonPropertyName("adjudication")]
    public ClaimAdjudication? Adjudication { get; set; }

    [JsonPropertyName("submitted_at")]
    public DateTimeOffset? SubmittedAt { get; set; }

    [JsonPropertyName("updated_at")]
    public DateTimeOffset UpdatedAt { get; set; }
}

public sealed class ClaimLine
{
    [JsonPropertyName("line_number")]
    public long LineNumber { get; set; }

    [JsonPropertyName("code_system")]
    public string CodeSystem { get; set; } = string.Empty;

    [JsonPropertyName("code_system_version")]
    public string? CodeSystemVersion { get; set; }

    [JsonPropertyName("service_code")]
    public string ServiceCode { get; set; } = string.Empty;

    [JsonPropertyName("units")]
    public decimal Units { get; set; }

    [JsonPropertyName("amount")]
    public long Amount { get; set; }
}

public sealed class ClaimInputLinesItem
{
    [JsonPropertyName("code_system")]
    public string CodeSystem { get; set; } = string.Empty;

    [JsonPropertyName("code_system_version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public RequestValue<string?> CodeSystemVersion { get; set; }

    [JsonPropertyName("service_code")]
    public string ServiceCode { get; set; } = string.Empty;

    [JsonPropertyName("units")]
    public decimal Units { get; set; }

    [JsonPropertyName("amount")]
    public long Amount { get; set; }
}

public sealed class ClaimInput
{
    [JsonPropertyName("eligibility_check_id")]
    public string EligibilityCheckId { get; set; } = string.Empty;

    [JsonPropertyName("preauthorization_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public RequestValue<string?> PreauthorizationId { get; set; }

    [JsonPropertyName("session_id")]
    public string SessionId { get; set; } = string.Empty;

    [JsonPropertyName("provider_claim_reference")]
    public string ProviderClaimReference { get; set; } = string.Empty;

    [JsonPropertyName("evidence_refs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public RequestValue<IReadOnlyList<string>> EvidenceRefs { get; set; }

    [JsonPropertyName("lines")]
    public IReadOnlyList<ClaimInputLinesItem> Lines { get; set; } = Array.Empty<ClaimInputLinesItem>();
}

public sealed class ClaimInformationRequest
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "claim_information_request";

    [JsonPropertyName("reason_code")]
    public string ReasonCode { get; set; } = string.Empty;

    [JsonPropertyName("requested_evidence_types")]
    public IReadOnlyList<string> RequestedEvidenceTypes { get; set; } = Array.Empty<string>();

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("due_at")]
    public DateTimeOffset? DueAt { get; set; }

    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; set; }

    [JsonPropertyName("resolved_at")]
    public DateTimeOffset? ResolvedAt { get; set; }
}

public sealed class ClaimInformationRequestInput
{
    [JsonPropertyName("reason_code")]
    public string ReasonCode { get; set; } = string.Empty;

    [JsonPropertyName("requested_evidence_types")]
    public IReadOnlyList<string> RequestedEvidenceTypes { get; set; } = Array.Empty<string>();

    [JsonPropertyName("due_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public RequestValue<DateTimeOffset?> DueAt { get; set; }
}

public sealed class ClaimEvidenceInput
{
    [JsonPropertyName("information_request_id")]
    public string InformationRequestId { get; set; } = string.Empty;

    [JsonPropertyName("evidence_refs")]
    public IReadOnlyList<string> EvidenceRefs { get; set; } = Array.Empty<string>();
}

public sealed class ClaimAdjudicationLineAmount
{
    [JsonPropertyName("billed")]
    public long Billed { get; set; }

    [JsonPropertyName("allowed")]
    public long Allowed { get; set; }

    [JsonPropertyName("payer")]
    public long Payer { get; set; }

    [JsonPropertyName("patient_responsibility")]
    public long PatientResponsibility { get; set; }

    [JsonPropertyName("adjustment")]
    public long Adjustment { get; set; }
}

public sealed class ClaimAdjudicationLine
{
    [JsonPropertyName("line_number")]
    public long LineNumber { get; set; }

    [JsonPropertyName("amount")]
    public ClaimAdjudicationLineAmount Amount { get; set; } = new ClaimAdjudicationLineAmount();

    [JsonPropertyName("reason_codes")]
    public IReadOnlyList<string> ReasonCodes { get; set; } = Array.Empty<string>();
}

public sealed class ClaimAdjudicationInput
{
    [JsonPropertyName("policy_reference")]
    public string PolicyReference { get; set; } = string.Empty;

    [JsonPropertyName("policy_version")]
    public string PolicyVersion { get; set; } = string.Empty;

    [JsonPropertyName("reason_codes")]
    public IReadOnlyList<string> ReasonCodes { get; set; } = Array.Empty<string>();

    [JsonPropertyName("evidence_refs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public RequestValue<IReadOnlyList<string>> EvidenceRefs { get; set; }

    [JsonPropertyName("lines")]
    public IReadOnlyList<ClaimAdjudicationLine> Lines { get; set; } = Array.Empty<ClaimAdjudicationLine>();
}

public sealed class ClaimAdjudicationAmount
{
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    [JsonPropertyName("billed")]
    public long Billed { get; set; }

    [JsonPropertyName("payer")]
    public long Payer { get; set; }

    [JsonPropertyName("patient_responsibility")]
    public long PatientResponsibility { get; set; }

    [JsonPropertyName("adjustment")]
    public long Adjustment { get; set; }
}

public sealed class ClaimAdjudicationPolicy
{
    [JsonPropertyName("reference")]
    public string Reference { get; set; } = string.Empty;

    [JsonPropertyName("version")]
    public string Version { get; set; } = string.Empty;
}

public sealed class ClaimAdjudication
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "claim_adjudication";

    [JsonPropertyName("version")]
    public long Version { get; set; }

    [JsonPropertyName("decision")]
    public string Decision { get; set; } = string.Empty;

    [JsonPropertyName("amount")]
    public ClaimAdjudicationAmount Amount { get; set; } = new ClaimAdjudicationAmount();

    [JsonPropertyName("reason_codes")]
    public IReadOnlyList<string> ReasonCodes { get; set; } = Array.Empty<string>();

    [JsonPropertyName("policy")]
    public ClaimAdjudicationPolicy Policy { get; set; } = new ClaimAdjudicationPolicy();

    [JsonPropertyName("lines")]
    public IReadOnlyList<ClaimAdjudicationLine> Lines { get; set; } = Array.Empty<ClaimAdjudicationLine>();

    [JsonPropertyName("decided_at")]
    public DateTimeOffset DecidedAt { get; set; }
}

public sealed class RemittanceList
{
    [JsonPropertyName("object")]
    public string Object { get; set; } = "list";

    [JsonPropertyName("data")]
    public IReadOnlyList<Remittance> Data { get; set; } = Array.Empty<Remittance>();

    [JsonPropertyName("has_more")]
    public bool HasMore { get; set; }
}

public sealed class RemittanceAmount
{
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    [JsonPropertyName("paid")]
    public long Paid { get; set; }
}

public sealed class Remittance
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "remittance";

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("payer_reference")]
    public string PayerReference { get; set; } = string.Empty;

    [JsonPropertyName("amount")]
    public RemittanceAmount Amount { get; set; } = new RemittanceAmount();

    [JsonPropertyName("allocations")]
    public IReadOnlyList<RemittanceAllocation> Allocations { get; set; } = Array.Empty<RemittanceAllocation>();

    [JsonPropertyName("received_at")]
    public DateTimeOffset ReceivedAt { get; set; }

    [JsonPropertyName("reconciled_at")]
    public DateTimeOffset? ReconciledAt { get; set; }
}

public sealed class RemittanceAllocation
{
    [JsonPropertyName("claim_id")]
    public string ClaimId { get; set; } = string.Empty;

    [JsonPropertyName("paid_amount")]
    public long PaidAmount { get; set; }

    [JsonPropertyName("reason_codes")]
    public IReadOnlyList<string> ReasonCodes { get; set; } = Array.Empty<string>();
}

public sealed class RemittanceInput
{
    [JsonPropertyName("payer_reference")]
    public string PayerReference { get; set; } = string.Empty;

    [JsonPropertyName("currency")]
    public string Currency { get; set; } = string.Empty;

    [JsonPropertyName("received_at")]
    public DateTimeOffset ReceivedAt { get; set; }

    [JsonPropertyName("allocations")]
    public IReadOnlyList<RemittanceAllocationInput> Allocations { get; set; } = Array.Empty<RemittanceAllocationInput>();
}

public sealed class RemittanceAllocationInput
{
    [JsonPropertyName("claim_id")]
    public string ClaimId { get; set; } = string.Empty;

    [JsonPropertyName("paid_amount")]
    public long PaidAmount { get; set; }

    [JsonPropertyName("reason_codes")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public RequestValue<IReadOnlyList<string>> ReasonCodes { get; set; }
}

public sealed class WebhookEndpointList
{
    [JsonPropertyName("object")]
    public string Object { get; set; } = "list";

    [JsonPropertyName("data")]
    public IReadOnlyList<WebhookEndpoint> Data { get; set; } = Array.Empty<WebhookEndpoint>();

    [JsonPropertyName("has_more")]
    public bool HasMore { get; set; }
}

public sealed class WebhookEndpoint
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "webhook_endpoint";

    [JsonPropertyName("url")]
    public Uri Url { get; set; } = null!;

    [JsonPropertyName("events")]
    public IReadOnlyList<string> Events { get; set; } = Array.Empty<string>();

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; set; }

    [JsonPropertyName("disabled_at")]
    public DateTimeOffset? DisabledAt { get; set; }
}

public sealed class WebhookEndpointWithSecret
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "webhook_endpoint";

    [JsonPropertyName("url")]
    public Uri Url { get; set; } = null!;

    [JsonPropertyName("events")]
    public IReadOnlyList<string> Events { get; set; } = Array.Empty<string>();

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; set; }

    [JsonPropertyName("disabled_at")]
    public DateTimeOffset? DisabledAt { get; set; }

    [JsonPropertyName("signing_secret")]
    public string SigningSecret { get; set; } = string.Empty;
}

public sealed class WebhookEndpointInput
{
    [JsonPropertyName("url")]
    public Uri Url { get; set; } = null!;

    [JsonPropertyName("events")]
    public IReadOnlyList<string> Events { get; set; } = Array.Empty<string>();
}

public sealed class WebhookDelivery
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("object")]
    public string Object { get; set; } = "webhook_delivery";

    [JsonPropertyName("delivered")]
    public bool Delivered { get; set; }

    [JsonPropertyName("attempts")]
    public long Attempts { get; set; }

    [JsonPropertyName("response_status")]
    public long? ResponseStatus { get; set; }
}

/// <summary>Base type for a pre-authorization decision.</summary>
public abstract class PreauthorizationDecisionInput
{
    [JsonPropertyName("outcome")]
    public abstract string Outcome { get; }

    [JsonPropertyName("reason_codes")]
    public IReadOnlyList<string> ReasonCodes { get; set; } = Array.Empty<string>();

    [JsonPropertyName("policy_reference")]
    public string PolicyReference { get; set; } = string.Empty;

    [JsonPropertyName("policy_version")]
    public string PolicyVersion { get; set; } = string.Empty;

    [JsonPropertyName("evidence_references")]
    public IReadOnlyList<string> EvidenceReferences { get; set; } = Array.Empty<string>();
}

/// <summary>Approves a pre-authorization.</summary>
public sealed class ApprovePreauthorizationInput : PreauthorizationDecisionInput
{
    public override string Outcome => "approved";

    [JsonPropertyName("approved_amount")]
    public long ApprovedAmount { get; set; }

    [JsonPropertyName("valid_until")]
    public DateTimeOffset ValidUntil { get; set; }
}

/// <summary>Denies a pre-authorization.</summary>
public sealed class DenyPreauthorizationInput : PreauthorizationDecisionInput
{
    public override string Outcome => "denied";
}
